[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = ["corepack enable && corepack prepare pnpm@10.4.1 --activate"]

[phases.install]
cmds = ["cd client && pnpm install"]

[phases.build]
cmds = ["cd client && pnpm build"]

[start]
cmd = "cd client && node dist/index.js"
